### ISSUE TITLE
GlusterFS download link in Ubuntu README points to old semiosis PPA

### ISSUE THREAD

**Issue by marascio** [louiszuckerman/glusterfs-debian#4]
The download link on the main GlusterFS download page was recently updated to point to ppa:gluster rather than ppa:semiosis. However, the Ubuntu.README was not updated. For example: http://download.gluster.org/pub/gluster/glusterfs/3.5/3.5.3/Ubuntu/Ubuntu.README still points to ppa:semiosis.

**Comment by louiszuckerman** [comment]
Thanks for catching & pointing this out.  I've updated the Ubuntu.README files on download.gluster.org in the 3.4.6, 3.5.3, and 3.6.1 directories.  The new README is generic and points people to the [main Gluster Community page on launchpad](https://launchpad.net/~gluster).  This README should be copied forward for all future releases on download.gluster.org.  I'm not updating the README for older releases since launchpad does not keep old builds.

Thanks again!
